### ISSUE TITLE
Support for OpenAPI features like maxLength, format, default

### ISSUE THREAD

**Issue by amoghsharma1996** [zenclabs/api#1758]
I haven't been able to find a way to use common Swagger/OpenAPI features such as default values for types, maxLengths for type, etc.

For example, I have a type called TestRequest

```
export interface TestRequest {
     /** This is the description for this property */
     status: string;
}
```

and this translates to the YML after contract generation of 

```
status:
type: string
description: This is the description for this property
```

But there are additional annotations that Swagger normally supports that in the YML would like like

```
status:
type: string
description: This is the description
maxLength: 100
default: Active
```

Obviously I can go ahead and manually edit my YML to include these additional properties but the whole point is to use Spot and describe everything in typescript and then have the YML generated correctly. Are these sorts of additional property describers available in Spot or am I out of luck? I am looking for ways to do maxLength, format, default, minLength, etc. 

If they are not available, I feel like this is a very important use case so that we can write comprehensive specs in openAPI.

Thanks

**Comment by oben01** [comment]
Please see  https://github.com/airtasker/spot/issues/1367

**Comment by amoghsharma1996** [comment]
Appreciate it @oben01 . Digging through the commits that were merged to master and looking at the spec examples. This should definitely get on the Wiki though to avoid this situation! If that's something I can assist with (documentation) I'm happy to give it a shot over the next few weeks
